# Experiment 1: Tokenization, Stemming and Lemmatization

**NLP Lab – PCCoE M.Tech**

### Objective
Apply different tokenization, stemming, and lemmatization techniques to a given English text and compare the results in terms of vocabulary variation and semantic coherence.

**Libraries:** Python, spaCy, NLTK, pandas  
**spaCy model:** `en_core_web_sm`

## 1. Requirements and Setup

The lab manual requires Python 3.x, spaCy with the English model `en_core_web_sm`, NLTK, and Jupyter/VS Code.

Run the following installation cell **only if these packages/model are not already installed**.

## 2. Import Libraries and Load spaCy

In [1]:
import spacy
import nltk
import pandas as pd
from nltk.stem import PorterStemmer, SnowballStemmer

print("spaCy version:", spacy.__version__)
print("NLTK version:", nltk.__version__)

nlp = spacy.load("en_core_web_sm")
print("spaCy English model loaded successfully.")

spaCy version: 3.8.16
NLTK version: 3.9.2
spaCy English model loaded successfully.

## 3. Step 1 – Enter the Given Text

The following paragraph is the text specified in the lab manual. It can be replaced with the text supplied by the instructor if required.

In [2]:
text = """
Natural language processing helps computers understand human language.
Students are studying, researchers are studying, and the models have learned
from many documents. A good NLP system analyzes words, sentences, and meanings.
The systems were designed to process, processed, and processing large collections
of text efficiently.
""".strip()

print(text)
print("\nCharacter count:", len(text))

Natural language processing helps computers understand human language.
Students are studying, researchers are studying, and the models have learned
from many documents. A good NLP system analyzes words, sentences, and meanings.
The systems were designed to process, processed, and processing large collections
of text efficiently.

Character count: 330

## 4. Step 2 – Create the spaCy Document

In [3]:
doc = nlp(text)

print("Number of spaCy tokens:", len(doc))
print("First 30 spaCy tokens:")
print([token.text for token in doc[:30]])

Number of spaCy tokens: 59
First 30 spaCy tokens:
['Natural', 'language', 'processing', 'helps', 'computers', 'understand', 'human', 'language', '.', '\n', 'Students', 'are', 'studying', ',', 'researchers', 'are', 'studying', ',', 'and', 'the', 'models', 'have', 'learned', '\n', 'from', 'many', 'documents', '.', 'A', 'good']

## 5. Step 3 – Tokenization

### 5.1 Whitespace Tokenization
Whitespace tokenization simply splits the text wherever whitespace occurs. Therefore, punctuation may remain attached to words such as `language.`

In [4]:
whitespace_tokens = text.split()

print("Whitespace tokens:")
print(whitespace_tokens)

print("\nCount:", len(whitespace_tokens))

Whitespace tokens:
['Natural', 'language', 'processing', 'helps', 'computers', 'understand', 'human', 'language.', 'Students', 'are', 'studying,', 'researchers', 'are', 'studying,', 'and', 'the', 'models', 'have', 'learned', 'from', 'many', 'documents.', 'A', 'good', 'NLP', 'system', 'analyzes', 'words,', 'sentences,', 'and', 'meanings.', 'The', 'systems', 'were', 'designed', 'to', 'process,', 'processed,', 'and', 'processing', 'large', 'collections', 'of', 'text', 'efficiently.']

Count: 45

### 5.2 spaCy Word Tokenization

spaCy uses linguistic tokenization rules and separates punctuation from words.

In [5]:
spacy_tokens = [token.text for token in doc]

print("spaCy tokens:")
print(spacy_tokens)

print("\nCount:", len(spacy_tokens))

spaCy tokens:
['Natural', 'language', 'processing', 'helps', 'computers', 'understand', 'human', 'language', '.', '\n', 'Students', 'are', 'studying', ',', 'researchers', 'are', 'studying', ',', 'and', 'the', 'models', 'have', 'learned', '\n', 'from', 'many', 'documents', '.', 'A', 'good', 'NLP', 'system', 'analyzes', 'words', ',', 'sentences', ',', 'and', 'meanings', '.', '\n', 'The', 'systems', 'were', 'designed', 'to', 'process', ',', 'processed', ',', 'and', 'processing', 'large', 'collections', '\n', 'of', 'text', 'efficiently', '.']

Count: 59

### 5.3 spaCy Tokens Without Punctuation and Spaces

This filtered list is used for stemming, lemmatization, and vocabulary analysis.

In [6]:
filtered_doc_tokens = [
    token for token in doc
    if not token.is_space and not token.is_punct
]

clean_tokens = [token.text for token in filtered_doc_tokens]

print("Before filtering:", len(spacy_tokens))
print("After filtering: ", len(clean_tokens))
print("Removed:         ", len(spacy_tokens) - len(clean_tokens))

print("\nFiltered tokens:")
print(clean_tokens)

Before filtering: 59
After filtering:  45
Removed:          14

Filtered tokens:
['Natural', 'language', 'processing', 'helps', 'computers', 'understand', 'human', 'language', 'Students', 'are', 'studying', 'researchers', 'are', 'studying', 'and', 'the', 'models', 'have', 'learned', 'from', 'many', 'documents', 'A', 'good', 'NLP', 'system', 'analyzes', 'words', 'sentences', 'and', 'meanings', 'The', 'systems', 'were', 'designed', 'to', 'process', 'processed', 'and', 'processing', 'large', 'collections', 'of', 'text', 'efficiently']

### Tokenization Comparison

In [7]:
tokenization_summary = pd.DataFrame({
    "Method": [
        "Whitespace tokenization",
        "spaCy tokenization",
        "spaCy filtered tokenization"
    ],
    "Token Count": [
        len(whitespace_tokens),
        len(spacy_tokens),
        len(clean_tokens)
    ]
})

display(tokenization_summary)

                        Method  Token Count
0      Whitespace tokenization           45
1           spaCy tokenization           59
2  spaCy filtered tokenization           45

## 6. Step 4 – Stemming

Stemming applies heuristic rules and may produce a string that is not a valid English word. The lab manual specifically asks for both **PorterStemmer** and **SnowballStemmer**.

In [8]:
porter = PorterStemmer()
snowball = SnowballStemmer("english")

original_words = [
    token.text.lower()
    for token in filtered_doc_tokens
    if token.is_alpha
]

porter_stems = [porter.stem(word) for word in original_words]
snowball_stems = [snowball.stem(word) for word in original_words]

print("Porter stems:")
print(porter_stems)

print("\nSnowball stems:")
print(snowball_stems)

Porter stems:
['natur', 'languag', 'process', 'help', 'comput', 'understand', 'human', 'languag', 'student', 'are', 'studi', 'research', 'are', 'studi', 'and', 'the', 'model', 'have', 'learn', 'from', 'mani', 'document', 'a', 'good', 'nlp', 'system', 'analyz', 'word', 'sentenc', 'and', 'mean', 'the', 'system', 'were', 'design', 'to', 'process', 'process', 'and', 'process', 'larg', 'collect', 'of', 'text', 'effici']

Snowball stems:
['natur', 'languag', 'process', 'help', 'comput', 'understand', 'human', 'languag', 'student', 'are', 'studi', 'research', 'are', 'studi', 'and', 'the', 'model', 'have', 'learn', 'from', 'mani', 'document', 'a', 'good', 'nlp', 'system', 'analyz', 'word', 'sentenc', 'and', 'mean', 'the', 'system', 'were', 'design', 'to', 'process', 'process', 'and', 'process', 'larg', 'collect', 'of', 'text', 'effici']

### Porter vs Snowball – Different Outputs

This cell identifies words for which the two stemmers produce different stems.

In [9]:
stemmer_differences = pd.DataFrame([
    {
        "Word": word,
        "Porter": porter.stem(word),
        "Snowball": snowball.stem(word)
    }
    for word in original_words
    if porter.stem(word) != snowball.stem(word)
])

if stemmer_differences.empty:
    print("No Porter/Snowball differences found for this text.")
else:
    display(stemmer_differences.drop_duplicates().reset_index(drop=True))

No Porter/Snowball differences found for this text.

## 7. Step 5 – Lemmatization Using spaCy

Lemmatization maps words to their dictionary/base forms using linguistic information. spaCy's model also provides POS information, which helps explain why lemmatization is generally more interpretable than heuristic stemming.

In [10]:
lemmas = [
    token.lemma_.lower()
    for token in filtered_doc_tokens
    if token.is_alpha
]

print("spaCy lemmas:")
print(lemmas)

spaCy lemmas:
['natural', 'language', 'processing', 'help', 'computer', 'understand', 'human', 'language', 'student', 'be', 'study', 'researcher', 'be', 'study', 'and', 'the', 'model', 'have', 'learn', 'from', 'many', 'document', 'a', 'good', 'nlp', 'system', 'analyze', 'word', 'sentence', 'and', 'meaning', 'the', 'system', 'be', 'design', 'to', 'process', 'process', 'and', 'process', 'large', 'collection', 'of', 'text', 'efficiently']

## 8. Step 6 – POS, Stem and Lemma Inspection

The lab manual recommends inspecting POS and lemmas together to understand the linguistic difference between stemming and lemmatization.

In [11]:
word_analysis = pd.DataFrame({
    "Original": [token.text for token in filtered_doc_tokens if token.is_alpha],
    "POS": [token.pos_ for token in filtered_doc_tokens if token.is_alpha],
    "Porter Stem": [porter.stem(token.text.lower())
                    for token in filtered_doc_tokens if token.is_alpha],
    "Snowball Stem": [snowball.stem(token.text.lower())
                      for token in filtered_doc_tokens if token.is_alpha],
    "spaCy Lemma": [token.lemma_.lower()
                    for token in filtered_doc_tokens if token.is_alpha]
})

display(word_analysis)

       Original    POS Porter Stem Snowball Stem  spaCy Lemma
0       Natural    ADJ       natur         natur      natural
1      language   NOUN     languag       languag     language
2    processing   NOUN     process       process   processing
3         helps   VERB        help          help         help
4     computers   NOUN      comput        comput     computer
5    understand   VERB  understand    understand   understand
6         human    ADJ       human         human        human
7      language   NOUN     languag       languag     language
8      Students   NOUN     student       student      student
9           are    AUX         are           are           be
10     studying   VERB       studi         studi        study
11  researchers   NOUN    research      research   researcher
12          are    AUX         are           are           be
13     studying   VERB       studi         studi        study
14          and  CCONJ         and           and          and
15          the    DET         the           the          the
16       models   NOUN       model         model        model
17         have    AUX        have          have         have
18      learned   VERB       learn         learn        learn
19         from    ADP        from          from         from
20         many    ADJ        mani          mani         many
21    documents   NOUN    document      document     document
22            A    DET           a             a            a
23         good    ADJ        good          good         good
24          NLP  PROPN         nlp           nlp          nlp
25       system   NOUN      system        system       system
26     analyzes   VERB      analyz        analyz      analyze
27        words   NOUN        word          word         word
28    sentences   NOUN     sentenc       sentenc     sentence
29          and  CCONJ         and           and          and
30     meanings   NOUN        mean          mean      meaning
31          The    DET         the           the          the
32      systems   NOUN      system        system       system
33         were    AUX        were          were           be
34     designed   VERB      design        design       design
35           to   PART          to            to           to
36      process   VERB     process       process      process
37    processed   VERB     process       process      process
38          and  CCONJ         and           and          and
39   processing   VERB     process       process      process
40        large    ADJ        larg          larg        large
41  collections   NOUN     collect       collect   collection
42           of    ADP          of            of           of
43         text   NOUN        text          text         text
44  efficiently    ADV      effici        effici  efficiently

## 9. Step 7 – Comparison Table for Selected Words

These examples follow the lab manual's expected observations: `studying`, `studied`, `processing`, and `systems`.

In [12]:
selected_words = [
    "studying",
    "studied",
    "processing",
    "systems"
]

selected_rows = []

for word in selected_words:
    matches = [
        token for token in filtered_doc_tokens
        if token.is_alpha and token.text.lower() == word
    ]

    if matches:
        token = matches[0]
        selected_rows.append({
            "Original": token.text,
            "POS": token.pos_,
            "Porter Stem": porter.stem(word),
            "Snowball Stem": snowball.stem(word),
            "spaCy Lemma": token.lemma_.lower()
        })

selected_comparison = pd.DataFrame(selected_rows)
display(selected_comparison)

     Original   POS Porter Stem Snowball Stem spaCy Lemma
0    studying  VERB       studi         studi       study
1  processing  NOUN     process       process  processing
2     systems  NOUN      system        system      system

## 10. Step 8 – Compare Word Variations

A lower number of unique normalized forms indicates stronger vocabulary reduction, but it does **not** automatically mean better preprocessing. The normalized forms must also remain meaningful.

For stemming and lemmatization, the reduction percentage is calculated using the formula from the lab manual:

`Reduction % = (1 - normalized unique forms / original unique forms) × 100`

In [13]:
def reduction_percentage(original, normalized):
    original_unique = len(set(original))
    normalized_unique = len(set(normalized))

    if original_unique == 0:
        return 0.0

    return (1 - normalized_unique / original_unique) * 100

porter_reduction = reduction_percentage(original_words, porter_stems)
snowball_reduction = reduction_percentage(original_words, snowball_stems)
lemma_reduction = reduction_percentage(original_words, lemmas)

variation_metrics = pd.DataFrame({
    "Method": [
        "Original words",
        "Porter stemming",
        "Snowball stemming",
        "spaCy lemmatization"
    ],
    "Total Words": [
        len(original_words),
        len(porter_stems),
        len(snowball_stems),
        len(lemmas)
    ],
    "Unique Forms": [
        len(set(original_words)),
        len(set(porter_stems)),
        len(set(snowball_stems)),
        len(set(lemmas))
    ],
    "Reduction %": [
        0.0,
        round(porter_reduction, 2),
        round(snowball_reduction, 2),
        round(lemma_reduction, 2)
    ]
})

display(variation_metrics)

                Method  Total Words  Unique Forms  Reduction %
0       Original words           45            38         0.00
1      Porter stemming           45            35         7.89
2    Snowball stemming           45            35         7.89
3  spaCy lemmatization           45            35         7.89

## 11. Tokenization/Stemming/Lemmatization Result Table

The lab manual's result table asks for total tokens/words, unique forms, reduction percentage, and semantic coherence.

For **tokenization**, reduction percentage is not a meaningful normalization measure because tokenization changes token boundaries rather than normalizing word forms. Therefore, it is reported as `N/A` instead of inventing a misleading value.

In [14]:
result_table = pd.DataFrame({
    "Method": [
        "Whitespace tokenization",
        "spaCy tokenization",
        "Porter stemming",
        "Snowball stemming",
        "spaCy lemmatization"
    ],
    "Total Tokens/Words": [
        len(whitespace_tokens),
        len(spacy_tokens),
        len(porter_stems),
        len(snowball_stems),
        len(lemmas)
    ],
    "Unique Forms": [
        len(set(whitespace_tokens)),
        len(set(spacy_tokens)),
        len(set(porter_stems)),
        len(set(snowball_stems)),
        len(set(lemmas))
    ],
    "Reduction %": [
        "N/A",
        "N/A",
        round(porter_reduction, 2),
        round(snowball_reduction, 2),
        round(lemma_reduction, 2)
    ],
    "Semantic Coherence": [
        "Not applicable",
        "Not applicable",
        "Lower – stems may be truncated/non-words",
        "Lower – stems may be truncated/non-words",
        "Higher – generally interpretable base forms"
    ]
})

display(result_table)

,Method,Total Tokens/Words,Unique Forms,Reduction %,Semantic Coherence
0,Whitespace tokenization,45,40,N/A,Not applicable
1,spaCy tokenization,59,42,N/A,Not applicable
2,Porter stemming,45,35,7.89,Lower – stems may be truncated/non-words
3,Snowball stemming,45,35,7.89,Lower – stems may be truncated/non-words
4,spaCy lemmatization,45,35,7.89,Higher – generally interpretable base forms

## 12. Step 9 – Qualitative Semantic Coherence

The lab manual asks us to evaluate semantic coherence qualitatively. We check whether:
- normalized forms are valid/interpretable English words,
- related forms such as `study`, `studying`, and `studied` are reasonably normalized,
- stems look unnatural or truncated,
- lemmas preserve recognizable base forms.

A vocabulary reduction percentage alone is **not** sufficient to claim semantic superiority.

In [15]:
# Representative examples for qualitative observation

examples = ["studying", "studied", "processing", "systems"]

observation_rows = []

for word in examples:
    token = next(
        (t for t in filtered_doc_tokens
         if t.is_alpha and t.text.lower() == word),
        None
    )

    if token is not None:
        observation_rows.append({
            "Original": word,
            "Porter Stem": porter.stem(word),
            "Snowball Stem": snowball.stem(word),
            "spaCy Lemma": token.lemma_.lower(),
            "Observation": (
                "Lemma is a recognizable base word; stems may be truncated."
                if word in {"studying", "studied"}
                else
                "Normalization produces an interpretable form."
                if word == "processing"
                else
                "Plural normalization is clear."
            )
        })

observation_df = pd.DataFrame(observation_rows)
display(observation_df)

,Original,Porter Stem,Snowball Stem,spaCy Lemma,Observation
0,studying,studi,studi,study,Lemma is a recognizable base word; stems may b...
1,processing,process,process,processing,Normalization produces an interpretable form.
2,systems,system,system,system,Plural normalization is clear.

## 13. Step 10 – Sentence-Level Comparison

The lab manual uses this short sentence to demonstrate the difference between stemming and lemmatization.

In [16]:
sample = "The students were studying and the researchers studied the results."
sample_doc = nlp(sample)

sample_words = [token for token in sample_doc if token.is_alpha]

sample_porter = [porter.stem(token.text.lower()) for token in sample_words]
sample_snowball = [snowball.stem(token.text.lower()) for token in sample_words]
sample_lemmas = [token.lemma_.lower() for token in sample_words]

print("Original:")
print(sample)

print("\nPorter stems:")
print(sample_porter)

print("\nSnowball stems:")
print(sample_snowball)

print("\nspaCy lemmas:")
print(sample_lemmas)

Original:
The students were studying and the researchers studied the results.

Porter stems:
['the', 'student', 'were', 'studi', 'and', 'the', 'research', 'studi', 'the', 'result']

Snowball stems:
['the', 'student', 'were', 'studi', 'and', 'the', 'research', 'studi', 'the', 'result']

spaCy lemmas:
['the', 'student', 'be', 'study', 'and', 'the', 'researcher', 'study', 'the', 'result']

## 14. Final Summary

This summary is generated directly from the experiment results.

In [17]:
print("=" * 65)
print("EXPERIMENT 1 – TOKENIZATION, STEMMING AND LEMMATIZATION")
print("=" * 65)

print("\nTOKENIZATION")
print("Whitespace tokens              :", len(whitespace_tokens))
print("spaCy tokens                   :", len(spacy_tokens))
print("Filtered spaCy tokens         :", len(clean_tokens))

print("\nVOCABULARY")
for _, row in variation_metrics.iterrows():
    print(
        f"{row['Method']:25} | "
        f"Total = {row['Total Words']:2} | "
        f"Unique = {row['Unique Forms']:2} | "
        f"Reduction = {row['Reduction %']:.2f}%"
        if isinstance(row["Reduction %"], (int, float))
        else
        f"{row['Method']:25} | Total = {row['Total Words']:2} | Unique = {row['Unique Forms']:2}"
    )

print("\nOBSERVATION")
print("- Whitespace tokenization is simple, but punctuation can remain attached to words.")
print("- spaCy tokenization provides linguistically meaningful token boundaries and separates punctuation.")
print("- Porter and Snowball stemming reduce word forms using heuristic rules and may create truncated stems.")
print("- spaCy lemmatization generally produces more interpretable dictionary/base forms.")
print("- Vocabulary reduction should be considered together with semantic coherence.")

=================================================================
EXPERIMENT 1 – TOKENIZATION, STEMMING AND LEMMATIZATION
=================================================================

TOKENIZATION
Whitespace tokens              : 45
spaCy tokens                   : 59
Filtered spaCy tokens         : 45

VOCABULARY
Original words            | Total = 45 | Unique = 38 | Reduction = 0.00%
Porter stemming           | Total = 45 | Unique = 35 | Reduction = 7.89%
Snowball stemming         | Total = 45 | Unique = 35 | Reduction = 7.89%
spaCy lemmatization       | Total = 45 | Unique = 35 | Reduction = 7.89%

OBSERVATION
- Whitespace tokenization is simple, but punctuation can remain attached to words.
- spaCy tokenization provides linguistically meaningful token boundaries and separates punctuation.
- Porter and Snowball stemming reduce word forms using heuristic rules and may create truncated stems.
- spaCy lemmatization generally produces more interpretable dictionary/base forms.
- Vocabulary reduction should be considered together with semantic coherence.